# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Android NDK toolchain Setup
    uses: ravinderjangra/android-ndk-toolchain-setup@0.2
    with:
      # Android API
      api: '21' # default is 21
      # Platform arch
      arch: 'arm'
      # Path to use for NDK toolchain
      install-location: 'toolchains'
      force: true


    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo "::set-env name=ANDROID_NDK_ROOT::$ANDROID_SDK_ROOT/ndk-bundle"

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cd Substrate
        ndk-build
        echo Add other actions to build,
        echo test, and deploy your project.
        
      - name: check
      run: |
        file ./libs/armeabi-v7a/libsubstrate.so
